name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/yourrepo
            git pull origin main

            sudo cp index.html /var/www/html/
            sudo cp main.js /var/www/html/
            sudo cp styles.css /var/www/html/

            sudo systemctl restart httpd