name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:  
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Capstone-Project-Group5
            git pull origin main
            sudo rm -rf /var/www/html/*
            sudo cp -r index.html /var/www/html/
            sudo chmod 755 /var/www/html
            sudo find /var/www/html -type f -exec chmod 644 {} \;
            sudo find /var/www/html -type d -exec chmod 755 {} \;
            sudo systemctl restart httpd

      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Capstone-Project-Group5
            git pull origin main
            sudo rm -rf /var/www/html/*
            sudo cp -r index.html /var/www/html/
            sudo chmod 755 /var/www/html
            sudo find /var/www/html -type f -exec chmod 644 {} \;
            sudo find /var/www/html -type d -exec chmod 755 {} \;
            sudo systemctl restart httpd