name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Instance 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            if [ ! -d ~/Capstone-Project-Group5 ]; then
              git clone https://github.com/EnergyOG/Capstone-Project-Group5.git ~/Capstone-Project-Group5
            fi
            cd ~/Capstone-Project-Group5
            git fetch origin main
            git reset --hard origin/main
            sudo rm -rf /var/www/html/*
            sudo cp index.html main.js styles.css /var/www/html/
            sudo systemctl restart httpd

      - name: Deploy to EC2 Instance 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            if [ ! -d ~/Capstone-Project-Group5 ]; then
              git clone https://github.com/EnergyOG/Capstone-Project-Group5.git ~/Capstone-Project-Group5
            fi
            cd ~/Capstone-Project-Group5
            git fetch origin main
            git reset --hard origin/main
            sudo rm -rf /var/www/html/*
            sudo cp index.html main.js styles.css /var/www/html/
            sudo systemctl restart httpd